training_data_fname: "/mnt/disk12tb/METIS/PSI/datasets/ds_CVC_300nm_Nband_5lD_1e4.h5"  # path and filename of the training dataset.
model_dir: "/mnt/disk12tb/METIS/PSI/models/CVC_1e4_Z20_asym_lyot_vector2/"  # path and folder name of the model.
model_name: "resnet18"  # CNN name (choose between 'resnet18', 'resnet34', 'resnet50').
weights_init_dir: False  #"./models/model_130nm_test/"  # False to use ImageNet pretrained weights, otherwise path to a custom pretrained model.
split_train: 90  # percentage of the dataset to reserve for training the model.
nb_workers: 8  # number of workers for PyTorch DataLoader.
batch_size: 64  # size of the data fed into the CNN at once.
learning_rate: 2e-4  # rate at each the CNN weights are updated (starting value, decrease when plateau reached on validation loss).
optimizer_name: "SAM"  # training optimizer (choose between 'Adam' and 'SGD' (TBC) and SAM ).
n_epochs: 200  # number of training epochs (how many times the full dataset is fed to the CNN).
lr_patience: 15 #10  # learning rate patience: after how many epochs of no improvement in validation loss the learning rate should be divided by 2.
earlystop_patience: 30 #20  # after how many epochs of no improvement in validation loss the training should be stopped.

# OVERLAPPING CONFIGURATION PARAMS
# n_modes: 20  # number of Zernike modes to predict (same as in the data).
# dataset_size: 100  # dataset size (training + validation).
# n_channels: 1  # number of input channels to the CNN (1: in OR out-of-focus; 2: in AND out-of-focus).

